# Generated by Django 4.2.24 on 2025-10-03 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NormalUser', '0002_normaluser_created_at_normaluser_ip_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='normaluser',
            old_name='name',
            new_name='username',
        ),
    ]
