# Generated by Django 5.2.7 on 2025-10-31 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_delete_userprofile'),
        ('user_try', '0008_user_has_used_referral_alter_auditlog_action_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referrer_bonus', models.DecimalField(decimal_places=2, default=8.0, max_digits=10)),
                ('referee_bonus', models.DecimalField(decimal_places=2, default=5.0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_bonuses_received', to='user_try.user')),
                ('referee_transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referee_bonus', to='stocks.transaction')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_bonuses_given', to='user_try.user')),
                ('referrer_transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrer_bonus', to='stocks.transaction')),
            ],
            options={
                'verbose_name_plural': 'Referral bonuses',
                'ordering': ['-created_at'],
            },
        ),
    ]
