# Generated by Django 5.2.7 on 2025-10-31 14:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_stock_deleted_at_stock_market_cap_stock_volume_and_more'),
        ('user_try', '0009_user_email_activation_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('include_current_valuation', models.BooleanField(default=True)),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('CSV', 'CSV')], default='PDF', max_length=4)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('GENERATING', 'GENERATING'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED')], default='PENDING', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'csv'])])),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_requests', to='user_try.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
