# Generated by Django 4.2.24 on 2025-10-03 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NormalUser', '0001_initial'),
        ('gift', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='new_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='id_new_user', to='NormalUser.normaluser'),
        ),
    ]
