# Generated by Django 4.2.24 on 2025-10-03 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminUser', '0002_alter_adminuser_name'),
        ('NormalUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActiveAndDesactive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('adminUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions', to='adminUser.adminuser')),
                ('normal_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_activate', to='NormalUser.normaluser')),
            ],
        ),
    ]
