# Generated by Django 4.2.24 on 2025-10-03 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NormalUser', '0001_initial'),
        ('userActiveAndDesactive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractiveanddesactive',
            name='normal_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_activate', to='NormalUser.normaluser'),
        ),
    ]
