# Generated by Django 4.2.24 on 2025-10-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
