# Generated by Django 4.2.24 on 2025-10-08 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_try', '0003_remove_user_referral_code_remove_user_referred_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='code',
            new_name='referral_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_try.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('suspended', 'Suspended')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('standard', 'Standard'), ('admin', 'Admin'), ('vip', 'VIP')], default='standard', max_length=50),
        ),
    ]
