# Generated by Django 5.2.7 on 2025-10-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_try', '0006_user_auth0_id_alter_user_password_alter_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
