# Generated by Django 5.2.7 on 2025-10-31 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_try', '0007_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_used_referral',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('register', 'User Registration'), ('password_change', 'Password Change'), ('referral_used', 'Referral Code Used')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='user_try.user'),
        ),
    ]
