# Generated by Django 5.2.7 on 2025-10-31 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_try', '0008_user_has_used_referral_alter_auditlog_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_activation_sent',
            field=models.BooleanField(default=False),
        ),
    ]
