# Generated by Django 5.2.7 on 2025-11-02 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_try', '0009_user_email_activation_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_pending_sent',
            field=models.BooleanField(default=False),
        ),
    ]
