# Generated by Django 4.2.24 on 2025-09-30 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('user', 'Usuario'), ('vip', 'VIP')], default='user', max_length=10),
        ),
    ]
